### PR TITLE
Include binary files for beginners

### PR DESCRIPTION
**Pull request by sillyfrog**
If you are interested, I have updated the process and included pre-compiled binaries so someone can quickly update their Sonoff device. I have used  this on a few Sonoff's now and it's working great.

Thanks for your great work!

### CODE REVIEW

**Comment by fastriker** [comment]
I tested @sillyfrog 's version on my Sonoff S20. I can confirm that it works :) (on the second try for me). 
By the way, I use Ubuntu 16.04 with Python 3.4.3. 

Thank you @mirko for the amazing reverse engineering and the script. Thank you @sillyfrog for making it more easy to flash a custom firmware. If I forgot someone involved in this relay nice peace of software: Thank you too!

**Comment by krtschmr** [comment]
this needs to be merged!!!1111oneeleven

**Comment by corny** [comment]
Thank a lot @sillyfrog 
Very helpful!

**Comment by adborges** [comment]
@syllyfrog Im getting WARNING) error on read: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2083)

using puthon 3.5.3 - MacOS

**Comment by sillyfrog** [comment]
@adborges I did all my dev on Mac, so it should just work, what are the lines in the logs leading up to that? (I'm assuming it's running and asking for your WiFi username etc)

**Comment by blackrozes** [comment]
Great work! Thank you very much!

I tested it sucessfully with Sonoff Basic and Sonoff TH. Sorry (I vergot  witch version)

**Comment by mirko** [comment]
I'm sorry that I was absent the past weeks. Instead of maintaining a fork I'd rather suggest you becoming a dev on this project. Does this make sense to you?

**Comment by sillyfrog** [comment]
Makes sense - I'm happy either way :) 
I'm actually travelling this week as well, so can also look at next wee, but happy to manage the merge through and keep this as the primary project.
Cheers.

**Comment by mirko** [comment]
Perfect, just added you as collaborator.

**Comment by sillyfrog** [comment]
mirko has kindly given me commit rights, so I have committed these changes directly.

**Comment by mirko** [comment]
@sillyfrog is there a way to reach you via E-Mail, IRC, XMPP, you-name-it? Even your git-commit-emailaddress doesn't reveal any contact data :)

**Comment by sillyfrog** [comment]
@mirko Done, I have sent you an email. Cheers.

**Pull request closed without merging**
